@Library("shared-library@main") _
pipeline {
    agent any
    stages {
        stage('Example') {
            steps {
                script {
                    log.Info("Test Info")
                    log.Error("Test Error")
                    sh "sleep 10"
                }
            }
        }
    }
}
