@Library("shared-library@main") _
pipeline {
    agent any
    stages {
        stage('Example') {
            steps {
                log.Info("Test Info")
                log.Error("Test Error")
            }
        }
    }
}
